# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: 
#       - deploy_service
  
# jobs:
#   job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print
#         run: echo "hello"



on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    
jobs:
  cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Run task
      run: echo "This is a scheduled task."


